"""Interactive CLI for testing and visualizing Causa Orchestrator.

Allows you to interactively test and run:
1. Real Local SLM (Ollama gemma3) generating code & unit tests.
2. Real Agent CLIs (Codex, OpenCode, Gemini/Antigravity) spawned in Git worktrees.
3. Multi-Agent Swarm Simulation with Ferry concurrency protection & token leaderboards.
4. Live Host Discovery of installed agent CLIs on your machine.

Run with:
    python -m packages.astra.cli
"""

import os
import sys
import time
from typing import Optional

from packages.slm.client import LocalSLMClient
from packages.astra.agent_launcher import AgentLauncher, AgentCLIType
from packages.astra.planner import TaskPlanner, ModelTier, SubTask
from packages.astra.supervisor import SwarmSupervisor
from packages.ferry.proxy import FerryProxy
from packages.ferry.lock_manager import LockManager
from packages.ferry.blackboard import Blackboard

BOLD = "\033[1m"
CYAN = "\033[96m"
GREEN = "\033[92m"
YELLOW = "\033[93m"
MAGENTA = "\033[95m"
RED = "\033[91m"
RESET = "\033[0m"


def print_header():
    print(f"\n{BOLD}{CYAN}========================================================================{RESET}")
    print(f"{BOLD}{CYAN}          CAUSA :: MULTI-AGENT SWARM TESTBENCH & RUNNER                 {RESET}")
    print(f"{BOLD}{CYAN}========================================================================{RESET}\n")


def print_menu():
    print(f"{BOLD}Select an action to execute and observe:{RESET}")
    print(f"  {BOLD}1.{RESET} {GREEN}[REAL] Run Local SLM (Ollama gemma3){RESET} -> Generate tests & verify via Ferry")
    print(f"  {BOLD}2.{RESET} {YELLOW}[DISCOVERY] Inspect Installed Agent CLIs{RESET} (Codex, OpenCode, Gemini/Antigravity)")
    print(f"  {BOLD}3.{RESET} {CYAN}[SWARM SIM] Full 3-Tier Multi-Agent Swarm Simulation{RESET} (Frontier + Fast + SLM)")
    print(f"  {BOLD}4.{RESET} {MAGENTA}[FERRY] Run Ferry Pre-Commit & Concurrency Collision Test{RESET}")
    print(f"  {BOLD}5.{RESET} Exit\n")


def run_slm_test():
    print(f"\n{BOLD}{GREEN}---> Launching Real Local SLM Execution (Ollama)...{RESET}")
    from tests.test_real_model import test_with_real_model
    test_with_real_model()


def run_discovery():
    print(f"\n{BOLD}{YELLOW}---> Discovering Installed Coding Agent CLIs on your Host OS...{RESET}\n")
    found = AgentLauncher.discover_installed_agents()
    for name, path in found.items():
        if path:
            print(f"  [{GREEN}AVAILABLE{RESET}] {BOLD}{name:<18}{RESET} : {path}")
        else:
            print(f"  [{RED}NOT FOUND{RESET}] {BOLD}{name:<18}{RESET} : Not detected in PATH/AppData")

    print(f"\n{BOLD}Ready-to-use Command Templates Generated by Astra:{RESET}")
    for agent_type in [AgentCLIType.CODEX, AgentCLIType.OPENCODE, AgentCLIType.GEMINI_ANTIGRAVITY]:
        cmd, _ = AgentLauncher.build_command(
            agent_type=agent_type,
            prompt="Refactor auth service and add tests",
            working_dir=".",
        )
        print(f"\n  * {CYAN}{agent_type.value.upper()}{RESET} Launch Command:\n    {BOLD}{cmd}{RESET}")
    print()


def run_swarm_simulation():
    print(f"\n{BOLD}{CYAN}---> Running Astra 3-Tier Swarm Simulation...{RESET}")
    from packages.astra.demo import run_demo as run_astra_demo
    run_astra_demo()


def run_ferry_test():
    print(f"\n{BOLD}{MAGENTA}---> Running Ferry Concurrency & Syntax Collision Test...{RESET}")
    from packages.ferry.demo import run_demo as run_ferry_demo
    run_ferry_demo()


def main():
    print_header()
    
    # Check if arguments provided
    if len(sys.argv) > 1:
        arg = sys.argv[1].lower()
        if arg in ("--slm", "1"):
            run_slm_test()
            return
        elif arg in ("--discovery", "2"):
            run_discovery()
            return
        elif arg in ("--swarm", "3"):
            run_swarm_simulation()
            return
        elif arg in ("--ferry", "4"):
            run_ferry_test()
            return

    # Interactive mode
    while True:
        print_menu()
        choice = input(f"{BOLD}Enter choice [1-5]: {RESET}").strip()
        if choice == "1":
            run_slm_test()
        elif choice == "2":
            run_discovery()
        elif choice == "3":
            run_swarm_simulation()
        elif choice == "4":
            run_ferry_test()
        elif choice == "5" or choice.lower() in ("exit", "q"):
            print("Exiting Causa Testbench. Happy hacking!\n")
            break
        else:
            print(f"{RED}Invalid option. Please choose between 1 and 5.{RESET}\n")


if __name__ == "__main__":
    main()
